language: java
cache:
  directories:
    - "$HOME/.m2"
before_cache:
  - rm -rf $HOME/.m2/repository/com/github/forinil
jdk:
  - oraclejdk8
  - openjdk8
install:
  # - mvn dependency:go-offline -DexcludeGroupIds=com.github.forinil
  - true
script:
  - mkdir logs
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn test -B
  - rm -r logs
