language: java
cache:
  directories:
    - "$HOME/.m2"
before_cache:
  - rm -rf $HOME/.m2/repository/com/github/forinil
jdk:
  - oraclejdk8
  - openjdk8
install:
  # - ./mvnw dependency:go-offline -DexcludeGroupIds=com.github.forinil
  - true
script:
  - mkdir logs
  - ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - ./mvnw test -B
  - rm -r logs
